# Generated by Django 3.0.8 on 2020-08-23 07:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200823_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 7, 39, 57, 725029, tzinfo=utc)),
        ),
    ]
